# Generated by Django 5.1.7 on 2025-04-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('spotify_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=360)),
                ('image_url', models.URLField(max_length=360)),
                ('owner_id', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=360)),
                ('url', models.URLField(max_length=360)),
                ('spotify_url', models.URLField(max_length=360)),
            ],
        ),
    ]
