# Generated by Django 5.1.7 on 2025-04-05 14:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_topartist_toptrack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recentlyplayedtrack',
            name='track',
        ),
        migrations.RemoveField(
            model_name='recentlyplayedtrack',
            name='user',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='spotify_url',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='url',
        ),
        migrations.AddField(
            model_name='playlist',
            name='added_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='playlist',
            name='type',
            field=models.CharField(default='favourite', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='playlist',
            name='image_url',
            field=models.URLField(max_length=360, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner_name',
            field=models.CharField(max_length=30),
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_played_at', models.DateTimeField()),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.playlist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.track')),
            ],
        ),
        migrations.DeleteModel(
            name='FavouriteTrack',
        ),
        migrations.DeleteModel(
            name='RecentlyPlayedTrack',
        ),
    ]
