# Generated by Django 5.1.7 on 2025-04-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_playlisttrack_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genre', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('artists', models.ManyToManyField(to='items.artist')),
            ],
        ),
        migrations.DeleteModel(
            name='ArtistGenre',
        ),
    ]
